"""Initial banned-word list, migrated from the Arcane keyword filter.

Seeded into the database the first time the filter loads with an empty list.
After that the list is managed with /word add and /word remove; edits here do
not touch an already-seeded server.
"""

DEFAULT_BANNED_WORDS: tuple[str, ...] = (
    "abcd",
    "africoon americoon",
    "antinigger",
    "aperest",
    "arabs",
    "arabush",
    "aunt jemima",
    "beaner",
    "blackman",
    "bluegum",
    "buddhahead",
    "bulldike",
    "bulldyke",
    "butchdike",
    "camel jockey",
    "camelfucker",
    "chernozhopy",
    "chinaman",
    "ching chong",
    "chink",
    "christfag",
    "commie",
    "communist",
    "coon",
    "cracker",
    "cumskin",
    "curry muncher",
    "dike",
    "dothead",
    "dune coon",
    "dyke",
    "fag",
    "fag mag",
    "faggot",
    "gatorbait",
    "gayslop",
    "goy",
    "goyslop",
    "israel",
    "israeli",
    "jew",
    "jew down",
    "jewish lightning",
    "jewnited snakes",
    "jewy",
    "jigaboo",
    "kyke",
    "lesbo",
    "malingsialan",
    "mentally retarded",
    "mexicoon",
    "midget",
    "muslim",
    "nagga",
    "negro",
    "nigfant",
    "nigga",
    "nigga please",
    "nigger",
    "nigger rigged",
    "nigger toe",
    "niggeration",
    "niggerbitch",
    "niggerboy",
    "niggercide",
    "niggerdick",
    "niggerette",
    "niggerfuck",
    "niggergram",
    "niggerization",
    "niggerosity",
    "niggerous",
    "niggerphile",
    "niggerskin",
    "nizzle",
    "paki",
    "piefke",
    "porch monkey",
    "porchmonkey",
    "prairie nigger",
    "queer",
    "retard",
    "sand nigger",
    "sandnigger",
    "she he",
    "shemale",
    "shitnigger",
    "snownigger",
    "spaz",
    "spearchucker",
    "sweat like a nigger",
    "tard",
    "tardbrain",
    "timbernigger",
    "towel head",
    "tranny",
    "transgendered",
    "troon",
    "turd world",
    "uncle tom",
    "white nigger",
    "yard ape",
    "yellow nigger",
    "zhidovka",
    "zhyd",
    "zionazi",
    "zipperhead",
)
